"""
PramaanX - Person 3: Analysis Hash / H2

Responsibilities:
1. Creating canonical ANALYSIS payload.
2. Combining the analysis result with H1.
3. Generating H2 using SHA-256.
4. Verifying H2 against a previously stored H2.

Hash chain:

    H1 = INPUT
    H2 = ANALYSIS + H1
    H3 = FINAL + H2

Canonical JSON:

    json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":")
    )
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Dict


def canonical_json(payload: Dict[str, Any]) -> str:
    """
    Convert a payload into deterministic canonical JSON.

    All team members must use the same serialization rules.
    """

    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":")
    )


def sha256_canonical(payload: Dict[str, Any]) -> str:
    """
    Calculate SHA-256 hash of canonical JSON.
    """

    canonical = canonical_json(payload)

    return hashlib.sha256(
        canonical.encode("utf-8")
    ).hexdigest()


def build_analysis_payload(
    verification_id: str,
    analysis_result: Dict[str, Any],
    previous_hash: str,
) -> Dict[str, Any]:
    """
    Build the canonical ANALYSIS payload.

    Parameters
    ----------
    verification_id:
        Unique PramaanX verification ID.

    analysis_result:
        Existing AI/tampering-analysis result from PramaanX.

    previous_hash:
        H1 generated by the INPUT layer.

    Returns
    -------
    dict
        ANALYSIS payload.
    """

    if not verification_id:
        raise ValueError("verification_id is required")

    if not previous_hash:
        raise ValueError("previous_hash (H1) is required")

    if not isinstance(analysis_result, dict):
        raise TypeError(
            "analysis_result must be a dictionary"
        )

    payload = {
        "analysis_result": analysis_result,
        "previous_hash": previous_hash,
        "record_type": "ANALYSIS",
        "verification_id": verification_id,
    }

    return payload


def generate_h2(
    verification_id: str,
    analysis_result: Dict[str, Any],
    previous_hash: str,
) -> str:
    """
    Generate H2 for the ANALYSIS checkpoint.

    H2 is calculated from the canonical ANALYSIS payload
    containing the previous INPUT hash H1.
    """

    payload = build_analysis_payload(
        verification_id=verification_id,
        analysis_result=analysis_result,
        previous_hash=previous_hash,
    )

    return sha256_canonical(payload)


def verify_h2(
    verification_id: str,
    analysis_result: Dict[str, Any],
    previous_hash: str,
    stored_hash: str,
) -> bool:
    """
    Recalculate H2 and compare it against stored H2.

    Returns
    -------
    bool
        True  -> MATCH
        False -> MISMATCH
    """

    current_hash = generate_h2(
        verification_id=verification_id,
        analysis_result=analysis_result,
        previous_hash=previous_hash,
    )

    return current_hash == stored_hash


# ============================================================
# INDEPENDENT P3 TEST
# ============================================================

if __name__ == "__main__":

    print("=" * 70)
    print("PramaanX — Person 3")
    print("ANALYSIS / H2 Independent Test")
    print("=" * 70)

    verification_id = "PX001"

    # Dummy H1 supplied by Person 2 during independent development.
    dummy_h1 = (
        "1111111111111111111111111111111111111111111111111111111111111111"
    )

    # This mirrors the normalized tampering result
    # produced by the existing PramaanX backend.
    dummy_analysis_result = {
        "status": "completed",
        "detected": False,
        "confidence": 0.1375,
        "note": (
            "Confidence score from ResNet18 binary classifier "
            "(genuine vs tampered). No heatmap or regional localisation "
            "is available from the current model."
        ),
        "error": None,
    }

    # Generate H2.
    h2 = generate_h2(
        verification_id=verification_id,
        analysis_result=dummy_analysis_result,
        previous_hash=dummy_h1,
    )

    print("\nVerification ID:")
    print(verification_id)

    print("\nH1:")
    print(dummy_h1)

    print("\nGenerated H2:")
    print(h2)

    # Verify H2.
    result = verify_h2(
        verification_id=verification_id,
        analysis_result=dummy_analysis_result,
        previous_hash=dummy_h1,
        stored_hash=h2,
    )

    print("\nVerification:")
    print("MATCH" if result else "MISMATCH")

    print("\n" + "=" * 70)